<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_MultipleSelection</name>
   <tag></tag>
   <elementGuidId>b14cfd70-0f14-4dd8-8d3f-5c004a9eea1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//mat-select[@aria-label='Toppings'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//mat-select[@aria-label='Toppings'])[1]</value>
   </webElementProperties>
</WebElementEntity>
